meilisearch:
  url: '%env(MEILISEARCH_URL)%'
  api_key: '%env(MEILISEARCH_API_KEY)%'
  prefix: '%env(MEILISEARCH_PREFIX)%'
  indices:
    - name: posts_fr
      class: App\Entity\Post
      enable_serializer_groups: true
      settings:
        localizedAttributes:
          - attributePatterns: ['*']
            locales: ['fr']
        searchableAttributes:
          - title
          - excerpt
          - metaDescription
          - categoryTitle
          - tags
        filterableAttributes:
          - id
          - categoryId
          - difficulty
          - isActive
          - createdAt
          - locale
        sortableAttributes:
          - createdAt
          - readingTime
          - cookingTime
        displayedAttributes:
          - id
          - title
          - slug
          - excerpt
          - metaDescription
          - categoryTitle
          - categorySlug
          - tags
          - difficulty
          - readingTime
          - cookingTime
          - isActive
          - createdAt
          - locale
          - url

    - name: posts_en
      class: App\Entity\Post
      enable_serializer_groups: true
      settings:
        localizedAttributes:
          - attributePatterns: ['*']
            locales: ['en']
        searchableAttributes:
          - title
          - excerpt
          - metaDescription
          - categoryTitle
          - tags
        filterableAttributes:
          - id
          - categoryId
          - difficulty
          - isActive
          - createdAt
          - locale
        sortableAttributes:
          - createdAt
          - readingTime
          - cookingTime
        displayedAttributes:
          - id
          - title
          - slug
          - excerpt
          - metaDescription
          - categoryTitle
          - categorySlug
          - tags
          - difficulty
          - readingTime
          - cookingTime
          - isActive
          - createdAt
          - locale
          - url
