---
apiVersion: v1
kind: Secret
metadata:
  name: tinie-bakerie-secrets
  namespace: tinie-bakerie
type: Opaque
stringData:
  POSTGRES_USER: "app"
  POSTGRES_PASSWORD: "k3s-tinie-bakerie-secret"
  POSTGRES_DB: "app"
  APP_SECRET: "k3s-app-secret-change-in-production"
  DATABASE_URL: "postgresql://app:k3s-tinie-bakerie-secret@postgres:5432/app?serverVersion=16&charset=utf8"
