App\Entity\CategoryTranslation:
    properties:
        title:
            - NotBlank:
                message: 'category_translation.title.not_blank'
            - Length:
                min: 3
                max: 255
                minMessage: 'category_translation.title.min_length'
                maxMessage: 'category_translation.title.max_length'

