App\Entity\CategoryMedia:
    properties:
        position:
            - NotNull: ~
            - Type: 
                type: integer
            - GreaterThanOrEqual:
                value: 0
                message: 'category_media.position.gte'
        translations:
            - Valid: ~
            - App\Validator\Constraints\ValidTranslations: ~

