App\Entity\PostMedia:
    properties:
        position:
            - NotNull: ~
            - Type: 
                type: integer
            - GreaterThanOrEqual:
                value: 0
                message: 'post_media.position.gte'
        translations:
            - Valid: ~
            - App\Validator\Constraints\ValidTranslations: ~
