App\Entity\Post:
    properties:
        category:
            - NotNull:
                message: 'post.category.not_null'
                groups: ['create', 'update', 'admin']
        tags:
            - Valid: 
                groups: ['create', 'update', 'admin']
        media:
            - Valid: 
                groups: ['create', 'update', 'admin']
        sections:
            - Valid: 
                groups: ['create', 'update', 'admin']
        readingTime:
            - NotNull: 
                groups: ['create', 'update', 'admin']
            - Type: 
                type: integer
                groups: ['create', 'update', 'admin']
            - GreaterThanOrEqual:
                value: 0
                message: 'post.reading_time.gte'
                groups: ['create', 'update', 'admin']
            - LessThanOrEqual:
                value: 300
                message: 'post.reading_time.lte'
                groups: ['create', 'update', 'admin']
        cookingTime:
            - NotNull: 
                groups: ['create', 'update', 'admin']
            - Type: 
                type: integer
                groups: ['create', 'update', 'admin']
            - GreaterThanOrEqual:
                value: 0
                message: 'post.cooking_time.gte'
                groups: ['create', 'update', 'admin']
            - LessThanOrEqual:
                value: 1440
                message: 'post.cooking_time.lte'
                groups: ['create', 'update', 'admin']
        difficulty:
            - NotNull: 
                groups: ['create', 'update', 'admin']
        translations:
            - Valid: 
                groups: ['create', 'update', 'admin']
            - App\Validator\Constraints\ValidTranslations: 
                groups: ['create', 'update', 'admin']
