App\Entity\PostTranslation:
    properties:
        title:
            - NotBlank:
                message: 'post_translation.title.not_blank'
            - Length:
                min: 3
                max: 255
                minMessage: 'post_translation.title.min_length'
                maxMessage: 'post_translation.title.max_length'
