# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    default_locale: fr
    app.supported_locales: 'fr|en'
    media_original_path: '%kernel.project_dir%/public/media/original'
    media_cache_path: '%kernel.project_dir%/public/media/cache'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Interface bindings
    App\Repository\PostSearchRepositoryInterface:
        alias: App\Repository\PostSearchRepository

    # Flysystem adapters for JoliCode Media Bundle
    filesystem.adapter.original:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments:
            - '%media_original_path%'

    filesystem.adapter.cache:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments:
            - '%media_cache_path%'

    filesystem.original.storage:
        class: League\Flysystem\Filesystem
        arguments:
            - '@filesystem.adapter.original'

    filesystem.cache.storage:
        class: League\Flysystem\Filesystem
        arguments:
            - '@filesystem.adapter.cache'
